# gallery-db-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gallery-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gallery-sc-retain