apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gallery-sc-retain
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate