# gallery-nfs-server.yaml
# gcloud compute disks create --size=10GB --zone=asia-east1-a gce-nfs-disk
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gallery-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
      role: nfs-server
  serviceName: "gallery-nfs-server"
  template:
    metadata:
      labels:
        app: gallery
        role: nfs-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gallery-nfs-server
        image: gcr.io/google_containers/volume-nfs
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: disk-for-nfs
      volumes:
        - name: disk-for-nfs
          gcePersistentDisk:
            pdName: gce-nfs-disk
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: gallery-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  clusterIP: None
  selector:
    app: gallery
    role: nfs-server
