# gallery-image-hub.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gallery-image-hub-pv
  labels:
    app: gallery
    role: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: gallery-nfs-server.default.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gallery-image-hub-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: gallery
      role: nfs-pv