# gallery-backend-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: gallery-backend-svc
spec:
  selector:
    app: gallery-backend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080